[package]
name = "aklogger"
version = "1.0.0"
edition = "2021"

[dependencies]
log = "0.4.19"
neon = "0.10.1"
once_cell = "1.18.0"
pyo3 = { version = "0.19.0", features = ["extension-module"] }

[lib]
name = "aklogger"
crate-type = ["cdylib"]
