version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-jessie-node
    steps:
      - checkout
      - restore_cache:
          key: v1-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install deps
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            poetry install
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Testing...
          command: |
            poetry run flake8
            poetry run py.test --cov=aklogger
      - run:
          name: Coverage Reporting
          command: |
            poetry run codecov -t $CODECOV_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - test
